### PR TITLE
doc: Misc. doc, README changes

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:
- Update correct SPDX license id
- Set changelog before readme in html doc
- Set source reference by tagged version
- Sort deps and format usage
- Badges and more badges!
- Add changelog link to hex info page
- Update contributing instruction

### CODE REVIEW

**Comment by asummers** [comment]
Wonderful! Thank you.

**Comment by asummers** [comment]
And this exposed a bug in my actions too. Fun times.

**Comment by kianmeng** [comment]
> And this exposed a bug in my actions too. Fun times.

Actions? As in GitHub Actions or? I've also noticed there are three CI setup, Travis CI, Circle CI, and GitHub Actions. Which is the current CI for this repo? :smile: 

Perhaps another PR to remove legacy CIs ?

**Comment by asummers** [comment]
Github Actions is the current one, but it's kind of half in, currently (got busy over the holidays as I was working on it). Eventually I will remove Circle and Travis entirely. 

It didn't pick up your PR because I think I have it set to only grab commits to this repo and yours was a fork, I think.

**Comment by kianmeng** [comment]
> Github Actions is the current one, but it's kind of half in, currently (got busy over the holidays as I was working on it). Eventually I will remove Circle and Travis entirely.
> 
> It didn't pick up your PR because I think I have it set to only grab commits to this repo and yours was a fork, I think.

I see. Do you know what bugs it exposed in the repo's GitHub Actions? I've checked the workflows, https://github.com/asummers/erlex/actions, seems to be passing?

**Pull request merged**
